### ISSUE TITLE
Synchronize env variables for ETL and Aggregation scripts

### ISSUE THREAD

**Issue by zelima** [cybergreen-net/infrastructure#10]
- [x] List out all env variable names here
- [x] decide which "stays" and which no

env variables for aggregator: 
```
STAGE  #dev or prod
RDS_PASSWORD
REDSHIFT_PASSWORD
CYBERGREEN_SOURCE_ROOT  #s3://private-bits-cybergreen-net/myenv/myfeed
CYBERGREEN_DEST_ROOT  #s3://bits.cybergreen.net/myenv/myfeed/myversion
AWS_ACCESS_KEY_ID
AWS_SECRET_ACCESS_KEY
```

**Comment by chorsley** [comment]
Shared values we might use between aggregator and ETL:

CYBERGREEN_SOURCE_ROOT
CYBERGREEN_DEST_ROOT

These may be an S3 path, e.g. s3://private-bits-cybergreen-net/dev/clean, or a local file path, e.g. /home/cguser/data/clean.

ETL specific:

CYBERGREEN_CONTAINER_REP

There may be more to come as we build in the ability to handle different infrastructure envs, but I'll keep this updates as they turn up.

It would be ideal if we could set a single set of env vars which are used across all elements of the pipeline. For customer env vars, may I suggest a prefix of `CYBERGREEN_` to avoid conflicts with other env variables?

**Comment by zelima** [comment]
@chorsley I modified configurations so that currently aggregator uses the following env variables:
```
STAGE - dev/prod/
RDS_PASSWORD
REDSHIFT_PASSWORD
CYBERGREEN_SOURCE_ROOT - s3://private-bits-cybergreen-net
CYBERGREEN_DEST_ROOT - s3://bits.cybergreen.net
AWS_ACCESS_KEY_ID
AWS_SECRET_ACCESS_KEY
```
You can see `config.json` here: https://gist.github.com/zelima/c777eb5230c96787821aff71d4f8e049

Any changes you'd like to see?

**Comment by chorsley** [comment]
Great stuff @zelima. A few comments:

* We use `$CYBERGREEN_SOURCE_ROOT` to set the entire bucket URI - that is `$CYBERGREEN_SOURCE_ROOT=s3://mybucket/myenv/myfeed`. This is because the root may be a local file path rather than an S3 path.  Could we reflect that in this config also?
* Do you mind renaming "STAGE" to "CYBERGREEN_BUILD_ENV" to align with ETL?

**Comment by zelima** [comment]
@chorsley sure, just I was using `$CYBERGREEN_SOURCE_ROOT` for s3 only so fat.. 
Will need to reconstruct a code to be compilable with local files as well.

**Comment by zelima** [comment]
@chorsley while working with local file paths I faced an issue:
- It is not possible to load files to Redshift from local files. I'm getting `LOAD source is not supported. (Hint: only S3 or DynamoDB or EMR based load is allowed)`
Meaning changing just `$CYBERGREEN_SOURCE_ROOT` and `$CYBERGREEN_DEST_ROOT` to local path won't work.

- Maybe we could use locally created db when using local paths?
- What should aggregator do when using local paths at all? (I was assuming the exact same thin, but without using s3 so far.)

**Comment by zelima** [comment]
@chorsley I assume we are synced on env variables. 

Currently aggregator does not support local file paths. We can open new issue if necessary.
Please confirm and we can close

**Comment by chorsley** [comment]
@zelima Sorry, missed your update from last week. Untested as yet, but looks good on the surface.

This is probably fine for now supporting only S3. We can come back to local file paths when they are required, but if the $CYBERGREEN_*_ROOT vars support s3://.../ paths, we can close for now pending further testing.

**Comment by zelima** [comment]
@chorsley great, closing for now.
