### ISSUE TITLE
Merge infrastructure and Orchestrator repos

### ISSUE THREAD

**Issue by zelima** [cybergreen-net/infrastructure#11]
For tracking already created issues here
- [ ] Rename this repo to orchestrator (If needed)
- [ ] Move scripts and docs from https://github.com/cybergreen-net/orchestrator here
- [ ] Delete original https://github.com/cybergreen-net/orchestrator

(Probably not in this order)

**Comment by chorsley** [comment]
Can you please check permissions on this repository? I don't seem to have push or management access to rename.

**Comment by zelima** [comment]
@chorsley should be fixed

**Comment by chorsley** [comment]
Thanks. I'll leave the name as Infrastructure for now to avoid confusion, but I've added the existing code and deleted the old repo now.
