### ISSUE TITLE
Be able to run orchestrator in docker (and ECS)

### ISSUE THREAD

**Issue by rufuspollock** [cybergreen-net/infrastructure#13]
Do what we need to do in code and docs to have orchestrator runnable in docker (and hence ECS)

**Comment by subhankarb** [comment]
FIXED.
Fixed with the commit 
- https://github.com/cybergreen-net/infrastructure/commit/53aca3a7cf5be2c76d8bbc6284c976037b6e243f
- https://github.com/cybergreen-net/infrastructure/commit/b2cdd11b84c86ffa8ddda0fd62dcbf95bab9975f
