### ISSUE TITLE
List infrastructure we deploy

### ISSUE THREAD

**Issue by rgrp** [cybergreen-net/infrastructure#2]
List infrastructure we need so we can look at automated this
- [ ] S3 buckets
  - output archive
  - public
  - raw (assume this exists as this is permanent)
- [ ] Redshift
- [ ] RDS
- [ ] Heroku
- [ ] Orchestrator (currently marjority is de facto orchestrator for ETL side at least - it fetches raw data, puts it up to S3, and also kicks off ETL jobs on ECS cluster)
- [ ] ECS cluster for running ETL jobs in parallel

**Comment by rgrp** [comment]
@chorsley @kxyne anything missing here for you guys? What about your EC2 instances / ECS stuff?

**Comment by chorsley** [comment]
Adding to that, we have:

- [ ] Orchestrator (currently marjorie is de facto orchestrator for ETL side at least - it fetches raw data, puts it up to S3, and also kicks off ETL jobs on ECS cluster)
- [ ] ECS cluster for running ETL jobs in parallel

**Comment by rgrp** [comment]
@chorsley perfect - please feel free to add main description to add this (and other items) as that will make it easier to see in one place.

**Comment by rgrp** [comment]
@chorsley do you want to merge? Once that is done i think we can close.

**Comment by rgrp** [comment]
FIXED. OK. I've merged your two items and think we can now close.
