### ISSUE TITLE
Boto vs Ansible vs Terraform for infrastructure management

### ISSUE THREAD

**Issue by rgrp** [cybergreen-net/infrastructure#7]
It would be valuable to have a common toolkit for managing infrastructure automation across the various components of the analytics pipeline.

## Options

* Ansible
* Boto
* SaltStack
* Terraform
* ...

Based on our further evaluation @atomatichq we are inclined towards either Ansible or even raw Boto (and away from Terraform). Slight preference for Ansible.

@chorsley @kxyne any thoughts or experience?

**Comment by chorsley** [comment]
We (Cosive) are big fans of Ansible. Our current plan was to create Ansible playbooks to set up and reconfigure / upgrade the orchestrator as needed, at least to start with. That would include cron jobs and pulling in repos and configuring any software that needs to run there. 

Once we've identified what extent we can get dev / prod separation happening in the next few weeks before deadline, we can work out what infra will need to be stood up per-run, and what would be better as ongoing. Haven't looked at AWS infra with Ansible just yet, and if that makes the most sense.

**Comment by rgrp** [comment]
FIXED. Sounds like we go with Ansible 👍
